### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by llKoull** [cp3hnu/CPLoading#1]
Hello!!

First of all i want to thank you about this awesome library. I'm using It in one of my Apps and I think that it's really good-looking ^_^

The problem is that I'm migrating that App right now from Swift 2.2 to Swift 3.0 (the app is called YouTrend) but i think that there is some kind of problem with your library and cocoapods (maybe the podspec?) because when i do 'pod update' i'm always receiving the 1.2.0 version that It's not compatible with the new version of Swift.

As i saw, you updated this library 13 days ago, but i've been comparing the coda that i have 'updated' and the code that you've posted on git and it is not the same you fixed all the errors that the compiling is giving to me but i'm not able to download the new code trough cocoapods.

Can you help me?

Thanks and best regards!

**Comment by cp3hnu** [comment]
CocoaPod had a problem. Please wait a moment.

**Comment by cp3hnu** [comment]
V2.0.1 re-written by Swift 3 is available in Cocoapod.

**Comment by llKoull** [comment]
Great! Thanks cp3hnu! ^_^
